In [2]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

In [7]:
df1=pd.read_csv(r"c:\Users\H.srinivas\Downloads\archive\global_food_wastage_dataset.csv")
df1_clean=df1.dropna()
df1

,Country,Year,Food Category,Total Waste (Tons),Economic Loss (Million $),Avg Waste per Capita (Kg),Population (Million),Household Waste (%)
0,Australia,2019,Fruits & Vegetables,19268.63,18686.68,72.69,87.59,53.64
1,Indonesia,2019,Prepared Food,3916.97,4394.48,192.52,1153.99,30.61
2,Germany,2022,Dairy Products,9700.16,8909.16,166.94,1006.11,48.08
3,France,2023,Fruits & Vegetables,46299.69,40551.22,120.19,953.05,31.91
4,France,2023,Beverages,33096.57,36980.82,104.74,1105.47,36.06
...,...,...,...,...,...,...,...,...
4995,France,2021,Beverages,47524.74,48058.40,77.41,1087.46,39.73
4996,Australia,2021,Beverages,32337.72,32705.08,194.35,1336.32,64.83
4997,China,2018,Meat & Seafood,20640.96,22485.33,21.04,16.13,31.23
4998,Australia,2021,Beverages,26566.64,29357.57,197.14,1086.17,69.95
4999,France,2024,Bakery Items,8860.27,7360.38,51.50,879.67,54.27

In [8]:
df1.columns

Index(['Country', 'Year', 'Food Category', 'Total Waste (Tons)',
       'Economic Loss (Million $)', 'Avg Waste per Capita (Kg)',
       'Population (Million)', 'Household Waste (%)'],
      dtype='object')

In [9]:
df1.columns[0:5]

Index(['Country', 'Year', 'Food Category', 'Total Waste (Tons)',
       'Economic Loss (Million $)'],
      dtype='object')

In [10]:
df1.drop_duplicates()

,Country,Year,Food Category,Total Waste (Tons),Economic Loss (Million $),Avg Waste per Capita (Kg),Population (Million),Household Waste (%)
0,Australia,2019,Fruits & Vegetables,19268.63,18686.68,72.69,87.59,53.64
1,Indonesia,2019,Prepared Food,3916.97,4394.48,192.52,1153.99,30.61
2,Germany,2022,Dairy Products,9700.16,8909.16,166.94,1006.11,48.08
3,France,2023,Fruits & Vegetables,46299.69,40551.22,120.19,953.05,31.91
4,France,2023,Beverages,33096.57,36980.82,104.74,1105.47,36.06
...,...,...,...,...,...,...,...,...
4995,France,2021,Beverages,47524.74,48058.40,77.41,1087.46,39.73
4996,Australia,2021,Beverages,32337.72,32705.08,194.35,1336.32,64.83
4997,China,2018,Meat & Seafood,20640.96,22485.33,21.04,16.13,31.23
4998,Australia,2021,Beverages,26566.64,29357.57,197.14,1086.17,69.95
4999,France,2024,Bakery Items,8860.27,7360.38,51.50,879.67,54.27

In [11]:
df1.duplicated

<bound method DataFrame.duplicated of         Country  Year        Food Category  Total Waste (Tons)  \
0     Australia  2019  Fruits & Vegetables            19268.63
1     Indonesia  2019        Prepared Food             3916.97
2       Germany  2022       Dairy Products             9700.16
3        France  2023  Fruits & Vegetables            46299.69
4        France  2023            Beverages            33096.57
...         ...   ...                  ...                 ...
4995     France  2021            Beverages            47524.74
4996  Australia  2021            Beverages            32337.72
4997      China  2018       Meat & Seafood            20640.96
4998  Australia  2021            Beverages            26566.64
4999     France  2024         Bakery Items             8860.27

      Economic Loss (Million $)  Avg Waste per Capita (Kg)  \
0                      18686.68                      72.69
1                       4394.48                     192.52
2                       8909.16                     166.94
3                      40551.22                     120.19
4                      36980.82                     104.74
...                         ...                        ...
4995                   48058.40                      77.41
4996                   32705.08                     194.35
4997                   22485.33                      21.04
4998                   29357.57                     197.14
4999                    7360.38                      51.50

      Population (Million)  Household Waste (%)
0                    87.59                53.64
1                  1153.99                30.61
2                  1006.11                48.08
3                   953.05                31.91
4                  1105.47                36.06
...                    ...                  ...
4995               1087.46                39.73
4996               1336.32                64.83
4997                 16.13                31.23
4998               1086.17                69.95
4999                879.67                54.27

[5000 rows x 8 columns]>